
import { useBusinessStore } from '../src/lib/store';
import { initializeAutomation } from '../src/lib/automation';

// 1. Initialize System Simulation
console.log('--- STARTING VERIFICATION ---');
initializeAutomation();
// In a real app, this runs on mount, but store is singleton so it works here.

const store = useBusinessStore.getState();

// 2. Prepare Test Data
const testUser = {
    name: 'Verification User',
    email: `verify-${Date.now()}@example.com`,
    phone: '555-0199'
};

const testServiceId = 's-1'; // Initial Consultation (Free)
const testDate = '2026-03-15';
const testTime = '10:00';

// 3. Simulate Public Booking Flow

// Step A: Create Lead (happens when user submits booking details)
console.log(`\n[Step 1] Creating Lead for ${testUser.name}...`);
useBusinessStore.getState().addLead({
    name: testUser.name,
    email: testUser.email,
    phone: testUser.phone,
    status: 'new',
    source: 'Verification Script',
    notes: 'Generated by automated verification script'
});

// Verify Lead Created
const updatedStore = useBusinessStore.getState();
const lead = updatedStore.leads.find(l => l.email === testUser.email);

if (!lead) {
    console.error('❌ FAILED: Lead was not created in store.');
    process.exit(1);
}
console.log(`✅ SUCCESS: Lead created with ID: ${lead.id}`);
console.log('   Lead Status:', lead.status);


// Step B: Create Booking
console.log(`\n[Step 2] Creating Booking for ${testDate} at ${testTime}...`);
useBusinessStore.getState().addBooking({
    leadId: lead.id,
    serviceId: testServiceId,
    date: testDate,
    time: testTime,
    duration: 30,
    notes: 'Automated booking test'
});

// Verify Booking Created
const booking = useBusinessStore.getState().bookings.find(b => b.leadId === lead.id);

if (!booking) {
    console.error('❌ FAILED: Booking was not created in store.');
    process.exit(1);
}
console.log(`✅ SUCCESS: Booking created with ID: ${booking.id}`);
console.log('   Booking Status:', booking.status);


// Step C: Verify Automation (Welcome Message)
console.log('\n[Step 3] Verifying Automation (Welcome Message)...');
// The automation engine listens for LEAD_CREATED and sends a message
const messages = useBusinessStore.getState().messages.filter(m => m.leadId === lead.id);

if (messages.length > 0) {
    console.log(`✅ SUCCESS: Found ${messages.length} message(s) for lead.`);
    console.log(`   Message 1: "${messages[0].content}"`);
} else {
    console.error('❌ FAILED: No welcome message found. Automation event might not have fired.');
}

// Step D: Verify Activity Feed
console.log('\n[Step 4] Verifying Dashboard Activity Feed...');
const activities = useBusinessStore.getState().activityFeed.filter(a =>
    a.metadata?.leadId === lead.id || a.metadata?.bookingId === booking.id
);

if (activities.length > 0) {
    console.log(`✅ SUCCESS: Found ${activities.length} activity items.`);
    activities.forEach(a => console.log(`   - [${a.type}] ${a.title}`));
} else {
    console.warn('⚠️ WARNING: No activity items found for this flow.');
}

console.log('\n--- VERIFICATION COMPLETE ---');
